name: quiz_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  flutter_animate: ^4.5.2
  percent_indicator: ^4.2.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.2
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
